# Generated by Django 6.0.5 on 2026-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Собаки'), ('cat', 'Кошки'), ('bird', 'Птицы'), ('rodent', 'Грызуны'), ('fish', 'Рыбы')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
